import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.84.0";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const lovableApiKey = Deno.env.get('LOVABLE_API_KEY')!;

    const supabase = createClient(supabaseUrl, supabaseKey);

    console.log('Starting blog article generation...');

    // Topics related to Romanian invoicing, accounting, and business management
    const topics = [
      'Ghid complet pentru emiterea facturilor electronice în România - cum să folosești sistemul e-Factura',
      'SAF-T D406: Tot ce trebuie să știi despre raportarea contabilă obligatorie în 2025',
      'Cum să gestionezi TVA-ul corect pentru PFA și micro-întreprinderi în România',
      'Optimizarea gestiunii cheltuielilor pentru afaceri mici din România',
      'Integrarea cu SPV: ghid complet pentru business-uri românești',
      'Cele mai comune greșeli în facturare și cum să le eviți',
      'Automatizarea proceselor contabile pentru SRL-uri din România',
      'Regimul fiscal simplificat vs normal pentru micro-întreprinderi',
      'Cum să pregătești documentația pentru audit fiscal în România',
      'Ghid pentru deducerea cheltuielilor de transport și combustibil',
    ];

    // Select a random topic
    const topic = topics[Math.floor(Math.random() * topics.length)];
    console.log(`Selected topic: ${topic}`);

    // Generate article using Lovable AI
    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${lovableApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          {
            role: 'system',
            content: `Ești un expert contabil și consultant fiscal specializat în legislația română. 
            Scrie articole detaliate, practice și utile pentru antreprenori și business-uri mici din România.
            Articolele trebuie să fie în limba română, profesionale dar accesibile.
            Include exemple concrete, pași practici și sfaturi utile.
            Formatul: markdown cu secțiuni clare (##), liste bullet și paragrafe scurte pentru lizibilitate.`
          },
          {
            role: 'user',
            content: `Scrie un articol detaliat despre: ${topic}
            
            Structura:
            1. Introducere captivantă (2-3 paragrafe)
            2. 4-6 secțiuni principale cu subtitruri clare
            3. Exemple concrete și pași practici
            4. Concluzie cu cheie ideas și next steps
            
            Lungime: 1200-1500 cuvinte.
            Ton: profesional dar prietenos, util și acționabil.`
          }
        ],
      }),
    });

    if (!aiResponse.ok) {
      if (aiResponse.status === 429) {
        console.error('Rate limit exceeded');
        return new Response(JSON.stringify({ error: 'Rate limit exceeded' }), {
          status: 429,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      if (aiResponse.status === 402) {
        console.error('Payment required');
        return new Response(JSON.stringify({ error: 'AI credits exhausted' }), {
          status: 402,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      const errorText = await aiResponse.text();
      console.error('AI API error:', aiResponse.status, errorText);
      throw new Error(`AI API error: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    const content = aiData.choices?.[0]?.message?.content;

    if (!content) {
      throw new Error('No content generated by AI');
    }

    console.log('Article generated, length:', content.length);

    // Extract title and create excerpt
    const lines = content.split('\n').filter((line: string) => line.trim());
    const title = topic;
    
    // Create excerpt from first paragraph after title
    let excerpt = '';
    for (const line of lines) {
      if (line.trim() && !line.startsWith('#') && line.length > 50) {
        excerpt = line.substring(0, 160) + '...';
        break;
      }
    }

    // Generate slug
    const slug = title
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '') // Remove diacritics
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .substring(0, 100);

    // Calculate reading time (average 200 words per minute)
    const wordCount = content.split(/\s+/).length;
    const readingTime = Math.ceil(wordCount / 200);

    // Extract keywords for SEO
    const keywords = [
      'facturare',
      'contabilitate',
      'România',
      'SAF-T',
      'e-Factura',
      'TVA',
      'fiscalitate',
    ];

    // Insert article into database
    const { data: article, error: insertError } = await supabase
      .from('blog_posts')
      .insert({
        title,
        slug,
        excerpt,
        content,
        author: 'SmartInvoice Team',
        status: 'published',
        meta_description: excerpt,
        meta_keywords: keywords,
        reading_time_minutes: readingTime,
        published_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (insertError) {
      console.error('Error inserting article:', insertError);
      throw insertError;
    }

    console.log('Article published successfully:', article.id);

    return new Response(
      JSON.stringify({
        success: true,
        article: {
          id: article.id,
          title: article.title,
          slug: article.slug,
        },
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  } catch (error) {
    console.error('Error in generate-blog-article:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});