// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if credentials are configured
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || 
    SUPABASE_URL === 'your-project-url' || 
    SUPABASE_PUBLISHABLE_KEY === 'your-anon-key') {
  console.warn('⚠️ Supabase credentials not configured. Please see SETUP.md for instructions.');
}

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);